export const icons = {
  HTML5: { className: "devicon-html5-plain", color: "#E34F26" },
  CSS3: { className: "devicon-css3-plain", color: "#1572B6" },
  SASS: { className: "devicon-sass-original", color: "#CF649A" },
  TailwindCSS: { className: "devicon-tailwindcss-original", color: "#06B6D4" },
  Bootstrap: { className: "devicon-bootstrap-plain", color: "#7952B3" },
  JavaScript: { className: "devicon-javascript-plain colored", color: "#323330" },
  TypeScript: { className: "devicon-typescript-plain", color: "#3178C6" },
  MUI: { className: "devicon-materialui-plain", color: "#007FFF" },
  ChartJS: { svgLink: "/icons/chartjs.svg", color: "#ff6384" },
  React: { className: "devicon-react-original colored", color: "#20232A" },
  NextJS: { className: "devicon-nextjs-plain", color: "#20232A" },
  Redux: { className: "devicon-redux-original", color: "#764ABC" },
  SocketIO: { className: "devicon-socketio-original", color: "#20232A" },
  swiper: { className: "devicon-swiper-original", color: "#6332F6" },
  radixui: { svgLink: "/icons/radixui.svg", color: "#20232A" },
  lucide: { svgLink: "/icons/lucide.svg", color: "#8B5CF6" },
  framer: { className: "devicon-framermotion-original", color: "#0055FF" },
  ejs: { svgLink: "/icons/ejs.svg", color: "#323330" },
  alpineJS: { className: "devicon-alpinejs-original", color: "#77C1D2" },
  antDesign: { className: "devicon-antdesign-plain", color: "#4285eb" },
  shadcn: { svgLink: "/icons/shadcn.svg", color: "#20232A" },
  launchui: { svgLink: "/icons/launchui.svg", color: "#20232A" },
  MongoDB: { className: "devicon-mongodb-plain", color: "#47A248" },
  NodeJS: { className: "devicon-nodejs-plain colored", color: "#339933" },
  Express: { className: "devicon-express-original", color: "#20232A" },
  Capacitor: { className: "devicon-capacitor-plain", color: "#119EFF" },
  Electron: { className: "devicon-electron-original", color: "#47848F" },
  Google: { className: "devicon-google-plain", color: "#4285F4" },
  GitHubActions: { className: "devicon-githubactions-plain", color: "#2088FF" },
  Vite: { className: "devicon-vitejs-plain", color: "#646CFF" },
  Supabase: { className: "devicon-supabase-plain", color: "#3ECF8E" },
  Vercel: { className: "devicon-vercel-original", color: "#20232A" },
  NPM: { className: "devicon-npm-original-wordmark", color: "#CB3837" },
};

export type IconKey = keyof typeof icons;
