import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const mikhak = localFont({
  src: "../style/fonts/Mikhak-VF.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "مجید کارگر | برنامه نویس فرانت اند",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={mikhak.className}>
      <body>{children}</body>
    </html>
  );
}
