import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const mikhak = localFont({
  src: "../style/fonts/Mikhak-VF.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "مجید کارگر | برنامه نویس فرانت اند",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={mikhak.className}>
      <body className="bg-black">
        <div className="h-[100vh] bg-gradient-to-br from-zinc-900/0 via-zinc-900 to-zinc-900/0">
          {children}
        </div>
      </body>
    </html>
  );
}
