import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Roboto } from "next/font/google";

const mikhak = localFont({
  src: "../style/fonts/Mikhak-VF.ttf",
  display: "swap",
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "مجید کارگر | برنامه نویس فرانت اند",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={` ${mikhak.className} ${roboto.variable}`}
    >
      <body className="bg-black">{children}</body>
    </html>
  );
}
